### ISSUE TITLE
Saving game in Commander Keen games on a windows 8.1 tablet

### ISSUE THREAD

**Issue by bradweston** [gerstrong/Commander-Genius#216]
the games are running fine and also working with a gamepad running through an otg cable. but am unable to save my games in Commander keen with the onscreen keyboard or gamepad.
Help.

**Comment by gerstrong** [comment]
Hi, I'm guessing you downloaded the normal Win32 Build, because for RT I 
never created a release.

You can map any button in the config, so there is a "menu" button in the 
controls settings. Just map that to any of you gamepad buttons and you 
should be able to open up the menu anytime to save.

I'm currently working on a new overlay system in which a onscreen 
keyboard with an additional menu button will be presented between other 
goodies.

Regards,
- Gerd

Am 26.01.2015 um 15:20 schrieb bradweston:

**Comment by The-MAZZTer** [comment]
There doesn't seem to be a website for the Android port (which you guys don't seem to maintain), so I guess I gotta post it here... I can map an onscreen button to MENU in the Android port but pressing it does nothing... so it doesn't seem possible to save your game!
