### ISSUE TITLE
Keen 5 - Neutrino Burst - Impossible

### ISSUE THREAD

**Issue by Blackbird88** [gerstrong/Commander-Genius#226]
Impossible to get through this hole. I watched walkthrough of DOS version and the guy just jumped through it :(
![2015-06-28_00001](https://cloud.githubusercontent.com/assets/4414625/8397623/a3be95ae-1dd2-11e5-9a71-f43bfd3c33a8.jpg)

Still Windows and 1.8.2

Any cheat or something so I can progress at least? :/

**Comment by gerstrong** [comment]
Thanks for reporting! We had that problem before, this scene is pretty 
special, because narrower than that you don't get in Keen afaik. Going 
to look at that one again.


Am 28.06.2015 um 20:17 schrieb Blackbird88:

**Comment by Blackbird88** [comment]
Any way to skip the level in the meantime?

**Comment by gerstrong** [comment]
I would cheat in that case. In level you can disable the collision 
detection with F10+N. But enable F10+J first so you can fly because you 
going to fall through the floor.

On Map you can also use those Cheats and walk through the level blockages.

Pressing the combination again will disable the cheats.

Am 29.06.2015 um 11:23 schrieb Blackbird88:

**Comment by Blackbird88** [comment]
Thank you so much! That did the trick!

**Comment by gerstrong** [comment]
Fixed! 9dd2f499f72a0ae599629176ef2baa3dbaea6580
