### ISSUE TITLE
Framerate timming is still being calculated when frameskip is off 

### ISSUE THREAD

**Issue by vanfanel** [gerstrong/Commander-Genius#296]
Hi,

Time ago I requested that you disable frame timmmig calculations when using SDL2 because syncing to vsync is possible.
In turn, you added the possibility to disable frameskipping, but it does not work as intended: with frameskipping off, the animated tiles (spikes, tentacles...) on the scenary run "as fast as possible" but the game still runs at the specified framerate.
Can you *please* disable ALL frame timming calculations when frameskip is disabled? That way the ENTIRE game should run as fast as possible, and combining that with VSYNC ON, we should get PERFECT smooth scrolling.

**Comment by gerstrong** [comment]
@vanfanel: It seems I got you wrong.

CG has two routines that run in a cycle. I refer them to "Ponder" and "Render". The pondering should be done 120 times per second. That cycle is only for logic, not for rendering.

The rendering part can be configured to be 10, 20, 30, 60 FPS and so on. Now when frameskipping is disabled it renders as much as possible, but the logic is kept at 120 LPS (Logic per second).

If I remove the 120 LPS, the whole game is going to run extremly fast. I think this is not wanted or am I wrong? Have you seen the cycle code for Ponder and Render? What shall I change then?

If I have 120 LPS, it makes sense to have 120 FPS as max, because if you have more you just would render the same stuff again and again, or am I mistaken?

I can create another cycle, if that helps. The code of that is found under GsKit/GsApp.cpp method is runMainCycle()

**Comment by vanfanel** [comment]
@gerstrong : I don't get exactly how the logic works (why is it running 120 times per second exactly? It should run as many times per second as it's needed: as fast as possible if the game is running as fast as possible).
So, with framerate control OFF, yes, the game should run extremely fast: there's nothing wrong with that, because vsync is what should limit the game speed, NOT the internal game logic. Then we can have perfect smooth movement always, at as many frames per second as the monitor physical mode does.

**Comment by gerstrong** [comment]
The game logic uses cycle of 120 LPS. I think it is good enough for the normal gameplay in which everything can react just fine. I'm not sure anymore why that number, I guess twice of 60 fps is always good. It could be more or less, but 120 LPS is considered the normal speed and the whole gameplay feeling was adapted to that.

Well, I get your point. We can let run everything as fast as possible, but if with Vsync is set and it runs with 60 LPS everything the game speed would be halved.

Let me think in how to change that and make it better...

**Comment by vanfanel** [comment]
@gerstrong : Everything regarding game framerate should depend ONLY on vsync, that's the idea. Never introduce a delay on the video, etc. As fast as possible even if it means "absurd fast", because vsync will take care of it (SDL_Flip() will be blocking based on the physical video mode refresh rate = always smooth scrolls!)

**Comment by gerstrong** [comment]
@vanfanel Okay I made some slight changes. On my system, it feels a bit smoother, I like it. Is it better that way now?
Since 9341e3ef

**Comment by vanfanel** [comment]
@gerstrong : Sorry but, is that on a different branch or something? I can't see commit 9341e3ef on the master branch

**Comment by gerstrong** [comment]
The Changes are in GsKit. Just do a git submodule update in the CG Source and you should get them.Am 19.12.2017 10:06 nachm. schrieb The Last Cabra <notifications@github.com>:@gerstrong : Sorry but, is that on a different branch or something? I can't see commit 9341e3ef on the master branch

**Comment by gerstrong** [comment]
ahh, my bad. Commit now is pushed. Sorry for the delay.

**Comment by vanfanel** [comment]
@gerstrong : Does not build:

```
manuel@vader:~/src/Commander-Genius/b3$ make
[  1%] Building CXX object GsKit/CMakeFiles/GsKit.dir/base/GsPython.cpp.o
/home/manuel/src/Commander-Genius/GsKit/base/GsPython.cpp: In function ‘bool loadStrFunction(PyObject*, const string&, std::__cxx11::string&, int)’:
/home/manuel/src/Commander-Genius/GsKit/base/GsPython.cpp:141:63: error: ‘PyUnicode_AsUTF8’ was not declared in this scope
             char *str = PyUnicode_AsUTF8(objectsRepresentation) ;
                                                               ^
GsKit/CMakeFiles/GsKit.dir/build.make:185: recipe for target 'GsKit/CMakeFiles/GsKit.dir/base/GsPython.cpp.o' failed
make[2]: *** [GsKit/CMakeFiles/GsKit.dir/base/GsPython.cpp.o] Error 1
CMakeFiles/Makefile2:187: recipe for target 'GsKit/CMakeFiles/GsKit.dir/all' failed
make[1]: *** [GsKit/CMakeFiles/GsKit.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by gerstrong** [comment]
what is up here? Try to disable python in cmake. Maybe that helps. I will try that on another system.

**Comment by gerstrong** [comment]
I  have python 3.6.3 installed. You need python 3 if you want to use it with CG. It's optional though, you can disable it with cmake . -DUSE_PYTHON3=OFF

I can build it here just fine. I also find it strange, because nothing has been changed for python 3 in the last months. Trying out Debian, to see if I get that.

**Comment by gerstrong** [comment]
Tried it on a fresh deepin linux 15.5 and it compiled without problems. Can you take a look if the Python3 libs are installed on your system or just disable Python3?

**Comment by gerstrong** [comment]
@vanfanel Okay, I will make python as optional dependency by default.

Considering FRAMESKIP and VSYNC. 

With VSYNC=ON we have a loop executed where one cycle is:

Game logic once -> Render once

There are no delays at all this time. So I don't understand the problem really. How should it be done then?

With LogicLatency = 1.0/LPS and RenderLatency = 1.0/FPS

With VSYNC=OFF we have a loop executed where one cycle does this:

elapsed = check how much time passed since the last cycle -> 
perform as many Gamelogic steps with LogicLatency time until "elapsed" is reached ->
Render once->
Measure how much time passed for rendering and gamelogic steps so far->
and only Delay for RenderLatency if FRAMESKIP=ON

I think the options do not make sense for the code we have now. I will take a deeper look into this.

Why should the game logic run as fast as possible really? The user wants to have a comfortable experience in gameplay. With Rendering I can render as much as possible, but why insanely fast gameplay. We can add an option for that, but it should not be bound to frameskip or vsync in my opinion. Or do you refer Frameskip to logic frames?

Can you take a look at the code in GsApp.cpp from line 240-361?

I would like to know how you would implement it.

**Comment by vanfanel** [comment]
@gerstrong : I am thinking about that piece of code and I think I have this *almost* right, but please lend me a hand: If I do ponder(0), am I telling the logic code that I don't want ANY delay and the logic will be done as fast as possible?

**Comment by gerstrong** [comment]
@vanfanel : correct!

**Comment by gerstrong** [comment]
The argument you pass to ponder is still unsed. It was meant for telling the Game logic for how much time you do the logic (basically it is a timestep). But ponder will always do it as fast as possible.

**Comment by gerstrong** [comment]
https://gafferongames.com/post/fix_your_timestep/

This article also helped a bit...

**Comment by vanfanel** [comment]
@gerstrong : Thanks! One more question: where do you control the scrolling speed? I mean:
Let's start saying something we already know: the main game loop is "while(1)" in "runMainCycle()",
so the game iterates on "while(1)" continuously.

Now, imagine I am moving as fast as possible from left to right on a game, let's say Keen1. Does the engine produce one NEW frame on each "while(1)" iteration in "runMainCycle()"?
OR (and this is the important part) **are there iterations of "while(1)" where no new frames are produced and only input reading and game logic are done?**

**Comment by gerstrong** [comment]
Basically for scrolling there exist a buffer of 512x512 or 1024x1024 pixels, for what I remember. It is always larger than the game resolution. It like here:

http://lazyfoo.net/tutorials/SDL/30_scrolling/index.php

Depending on the amount scrolled the algorithm decides whether everything will be drawn or horizontal and/or vertical stripes of the backround. Sprites are fully rendered when Render() is called.

The scrollspeed is controlled by the CCamera class:

https://github.com/gerstrong/Commander-Genius/blob/89b6e0ae60d6248cb6974666677618fe2216b68b/src/engine/core/CCamera.cpp

It depends on where the player is. The camera cycle is part of the game logic like any other character used. There is a limit though if the player gets too much out of certain area. In that case it scrolls in a while until the player is centered more or less.

For Keen4 and Keen1 I find it strange you see some differences in smoothness. The scrolling engine used is the same.  Also that same class controls the scrolling. It might be related to something else, maybe more sprites processed, not sure...

**Comment by vanfanel** [comment]
@gerstrong : I have been taking a look at the code and, from your explanation, I understand the scrolling is done (on the CCamera class) depending on the characted getting to the center of the screen.
And you are right: code for Keen1-3 and Keen4 is the same regarding camera movement.
So I have been closely looking at how the characted moves in Keen1-3 versus how the character moves on Keen4, and there is the difference! In Keen4, the character moves smoothly as it walks (it moves pixel-per-pixel), while in Keen1-3 the character walks "in blocks": that makes the scroll different!!
So, can the walking logic from Keen4 be used in Keen1-3? That should make the scroll equally smooth!

**Comment by gerstrong** [comment]
Changing the walking logic would alter the physics. Keen 1-3 are meant to be like they are really and resemble the original pretty in that regard. Walking in blocks? Not sure if I get it. It seems to be smooth here on my machine as well. Keen does not walk "in blocks". At least for my understanding. Which part do you think make Keen 1-3 walk in blocks?

**Comment by vanfanel** [comment]
@gerstrong : I would say that, if the game movement speed in Keen1-3 can not be made to match that of Keen4, this is as far as we can get. At least, Keen4 is now perfectly smooth! Since you removed the daleays when VSYNC is ON, everything is MUCH better!
I think this issue can be closed now :)
