### ISSUE TITLE
1362 Floating point exception./CGeniusExe

### ISSUE THREAD

**Issue by ronilaukkarinen** [gerstrong/Commander-Genius#329]
The latest build with SDL Mixer 2 compile completed nicely (after figuring out the package [here](https://github.com/gerstrong/Commander-Genius/issues/326)), but unfortunately the emulator doesn't start.

runcommand.log:

````
Parameters: 
Executing: pushd /opt/retropie/ports/cgenius; ./CGeniusExe; popd
/opt/retropie/ports/cgenius ~
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1007:  1362 Floating point exception./CGeniusExe
~
````
What's causing this?

Using the latest retropie. 

Build couple of weeks back worked last time, I guess I need to revert.

**Comment by gerstrong** [comment]
It runs fine here. I also tagged it to another Release. Can you Run it with gdb, Just want to See where it crashes with fpe?Am 18.02.2018 6:19 nachm. schrieb Roni Laukkarinen <notifications@github.com>:The latest build with SDL Mixer 2 compile completed nicely (after figuring out the package here), but unfortunately the emulator doesn't start.
runcommand.log:
Parameters: 
Executing: pushd /opt/retropie/ports/cgenius; ./CGeniusExe; popd
/opt/retropie/ports/cgenius ~
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1007:  1362 Floating point exception./CGeniusExe
~

What's causing this?
Using the latest retropie.
Build couple of weeks back worked last time, I guess I need to revert.

**Comment by gerstrong** [comment]
Maybe retropie Commander Genius needs an Update. There were many issues with sdl Mixer, but they all should be fixed. Sdl Mixer Is really Worth. The audio Quality got much better since it implementation...Am 18.02.2018 6:19 nachm. schrieb Roni Laukkarinen <notifications@github.com>:The latest build with SDL Mixer 2 compile completed nicely (after figuring out the package here), but unfortunately the emulator doesn't start.
runcommand.log:
Parameters: 
Executing: pushd /opt/retropie/ports/cgenius; ./CGeniusExe; popd
/opt/retropie/ports/cgenius ~
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1007:  1362 Floating point exception./CGeniusExe
~

What's causing this?
Using the latest retropie.
Build couple of weeks back worked last time, I guess I need to revert.

**Comment by ronilaukkarinen** [comment]
I don't really know what needs to be updated in retropie script, you could look at [cgenius.sh](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/ports/cgenius.sh) in their repo?

How to run it with gdb? I think I need to edit retropie's runcommand for that...

**Comment by gerstrong** [comment]
No, this only builds CG and you need to build it in Debug now that I remember. That is more complex to Achive. Can you check which Version is being compiled? Under CMakelists.txt the First 10-20 lines should tell you the Version...Am 18.02.2018 7:40 nachm. schrieb Roni Laukkarinen <notifications@github.com>:I don't really know what needs to be updated in retropie script, you could look at cgenius.sh in their repo?
How to run it with gdb? I think I need to edit retropie's runcommand for that...

**Comment by gerstrong** [comment]
I compiled everything with using the latest and it runs just fine. is the path /opt/retropie/ports/cgenius writable. It shouldn't matter, but maybe it's a hint. Is nothing shown at all?
