### ISSUE TITLE
Cannot break any of the fuses in Keen 5

### ISSUE THREAD

**Issue by RahulSriram** [gerstrong/Commander-Genius#367]
I've been playing through the keen series lately on my android phone, using the [Commander Genius App](https://play.google.com/store/apps/details?id=net.sourceforge.clonekeenplus)
While everything has gone fine until now, I'm stuck at a place where I need to break this fuse, and it just wont budge, no matter what i do. I read online that a simple pogo jump should be enough to break it, but it doesn't work. I tried loading an earlier save and checking a different level which also happens to have a fuse, same problem.
Can you please check this out?
I am attaching a screen recording of the issue I'm seeing

https://user-images.githubusercontent.com/10979859/172044302-c337008f-7482-45b0-ba83-9031436ea428.mp4

**Comment by gerstrong** [comment]
Thanks for trying this out. I had issues in the past with the fuses, but it seems to be back. Let me take a look and return with a fix.

**Comment by gerstrong** [comment]
Can you please tell which version of Commander Genius you are using?

You can see that in the Game Launcher. Thanks in advance!

**Comment by RahulSriram** [comment]
Hey, thanks for looking into this! It was in version 3.0.9

**Comment by gerstrong** [comment]
I think it is fixed this time. There is just one catch: The bug is related to your saved game. If within the level you had saved, the fuse would not break anymore. For version 3.1.1 I got it fixed, but it might take some time to get that version released for android.

If you want to test it already, you can on a PC, download CG here: https://gitlab.com/Dringgstein/Commander-Genius/-/releases

Version 3.1.1 and later should have it working correctly now.

**Comment by RahulSriram** [comment]
Thank you! I will wait for the new version on android. I do have a save
that I did on the world map before entering the level, hope thats
good enough

**Comment by gerstrong** [comment]
Yes, the save on the world map will work.

**Comment by gerstrong** [comment]
We had a release on Juli 1st for Android. I couldn't reproduce this issue anymore. If you still have problems with it, feel free to reopen this ticket.
