### ISSUE TITLE
Can't comprehend keen 5 patches

### ISSUE THREAD

**Issue by VikingBoyBilly** [gerstrong/Commander-Genius#372]
Keen 1 Marooned on Mars Galaxy remake can't let you jump on yorps and statue texts don't appear.  Is this even an issue?

**Comment by gerstrong** [comment]
We had support for this some time ago when Python was still supported. But CG switched to Lua and we never ported that code. The python part was unfinished anyways, so we never had a proper version for that mod anyways.

It is a bit more work to support this mod, we can have a look if you are interested in mod development for CG. Otherwise I'd say for this mod to stick to a Keen5e.exe and Dosbox.
